on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  requirements_generation:
    name: generateRequirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate requirements file
        run: |
          pip3 install pip-tools
          pip install pandas requests fpdf pdfkit PyPDF2 plotly
          pip list --format=freeze > requirements.txt
      - name: Upload Requirements File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: requirementstxt
          path: requirements.txt
  semgrep_scan:
    needs: requirements_generation
    name: Semgrep scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: requirementstxt
      - run: semgrep ci --supply-chain --x-ls
